server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/agricultural_machinery
    name: root
    data-password: cyf1996
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
